iplanet-am-auth-oauth-auth-service=https://github.com/login/oauth/authorize
iplanet-am-auth-oauth-token-service=https://github.com/login/oauth/access_token
iplanet-am-auth-oauth-user-profile-service=https://api.github.com/user
iplanet-am-auth-oauth-scope=read:user user:email
iplanet-am-auth-oauth-sso-proxy-url=https://wrenam.wrensecurity.local:8443/auth/oauth2c/OAuthProxy.jsp
org-forgerock-auth-oauth-account-provider=org.forgerock.openam.authentication.modules.common.mapping.DefaultAccountProvider
org-forgerock-auth-oauth-account-mapper=org.forgerock.openam.authentication.modules.common.mapping.JsonAttributeMapper
org-forgerock-auth-oauth-account-mapper-configuration=login=uid
org-forgerock-auth-oauth-attribute-mapper=org.forgerock.openam.authentication.modules.common.mapping.JsonAttributeMapper
org-forgerock-auth-oauth-attribute-mapper-configuration=login=uid
org-forgerock-auth-oauth-save-attributes-to-session-flag=true
org-forgerock-auth-oauth-createaccount-flag=true
org-forgerock-auth-oauth-prompt-password-flag=false
org-forgerock-auth-oauth-map-to-anonymous-flag=false
org-forgerock-auth-oauth-logout-behaviour=donotlogout
openam-auth-openidconnect-crypto-context-type=client_secret
