# Token store exchange session-to-SAML instance
deployment-realm=/
deployment-url-element=session-to-saml
issuer-name=urn:wren:am:cookbook:token-exchange
persist-issued-tokens-in-cts=false
saml2-attribute-map=uid=uid
saml2-encrypt-assertion=false
saml2-encrypt-attributes=false
saml2-encrypt-nameid=false
saml2-encryption-algorithm=http://www.w3.org/2001/04/xmlenc#aes128-cbc
saml2-encryption-algorithm-strength=128
saml2-keystore-filename=/usr/local/tomcat/conf/wrenam-cookbook.p12
saml2-keystore-password=changeit
saml2-name-id-format=urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
saml2-sign-assertion=true
saml2-signature-key-alias=wrenam.wrensecurity.local
saml2-signature-key-password=changeit
saml2-sp-acs-url=https://service.example.com/saml/acs
saml2-sp-entity-id=urn:wren:am:cookbook:service-provider
saml2-token-lifetime-seconds=600
supported-token-transforms=OPENAM|SAML2|false
