clientsCanSkipConsent=false
forgerock-oauth2-provider-issue-refresh-token-on-refreshing-token=false
forgerock-oauth2-provider-supported-claims=name
forgerock-oauth2-provider-supported-claims=given_name
forgerock-oauth2-provider-supported-claims=family_name
forgerock-oauth2-provider-supported-claims=locale
forgerock-oauth2-provider-supported-claims=zoneinfo
forgerock-oauth2-provider-supported-scopes=openid|
forgerock-oauth2-provider-supported-scopes=profile|profile
