com.forgerock.openam.oauth2provider.clientType=Confidential
com.forgerock.openam.oauth2provider.clientName[0]=oidc-webapp
com.forgerock.openam.oauth2provider.redirectionURIs[0]=https://protected.wrensecurity.local:443/openid/callback
com.forgerock.openam.oauth2provider.responseTypes[0]=code
com.forgerock.openam.oauth2provider.scopes[0]=openid
com.forgerock.openam.oauth2provider.scopes[1]=profile
com.forgerock.openam.oauth2provider.subjectType=Public
com.forgerock.openam.oauth2provider.tokenEndPointAuthMethod=client_secret_basic
isConsentImplied=false
sunIdentityServerDeviceStatus=Active
userpassword=changeit
